spring: 
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: tis_prod
    url: ${db-url}
    username: tis_prod
    password: 12345
  database:
    driverClassName: org.postgresql.Driver
server:
  port: ${port}