name: Github CI
on:
  push:
    branches: [ "arquitetura" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Build
        run: |
          docker build Codigo/posto-ipiranga -t posto-ipiranga

          docker build Codigo/postoapp -t postoapp

      - name: tag
        run: |
          docker tag posto-ipiranga ${{ env.REGISTRY }}/plf-es-2023-2-ti3-6654100-posto-ipiranga/posto-ipiranga/posto-ipiranga:v1.0.0
          
          docker tag postoapp ${{ env.REGISTRY }}/plf-es-2023-2-ti3-6654100-posto-ipiranga/posto-ipiranga/front:v1.0.0

      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: PAlucas
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: |
          docker push  ${{ env.REGISTRY }}/plf-es-2023-2-ti3-6654100-posto-ipiranga/posto-ipiranga:v1.0.0

          docker push  ${{ env.REGISTRY }}/plf-es-2023-2-ti3-6654100-posto-ipiranga/postoapp:v1.0.0